name: deploy
on:
  push:
    branches: [master] # master 分支有 push 时触发
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      # 下载源码
      # 这一步就是检出你的仓库并下载里面的代码到runner中,actions/checkout@v2是官方自己造的轮子，直接拿来用就行
      - name: Checkout
        uses: actions/checkout@v2

      # 打包构建
      - name: Build
        uses: actions/setup-node@master
        with:
          node-version: "16.x"
      - run: npm install # 安装依赖
      - run: npm run build # 打包
      # 部署到 GitHub pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3 # 使用部署到 GitHub pages 的 action
        with:
          # # 部署到 gh-pages 分支
          branch: gh-pages
          # deploy_key: ${{ secrets.REACTSTATEMANAGE }} # 部署密钥，在项目的 Settings/Secrets 中配置
          publish_dir: ./dist # 部署打包后的 dist 目录
          github_token: ${{ secrets.REACTSTATEMANAGE }} # secret 名
          commit_message: 自动部署 # 部署时的 git 提交信息，自由填写
  deploy_backend:
    needs: deploy_frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # 在这里添加部署后端项目的步骤
      - name: Setup Node.js for backend
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install backend dependencies
        run: cd server && npm install

      # 在这里启动 Node.js 服务，并指定端口为 8080
      - name: Start Node.js server
        run: cd server && npm start
        env:
          PORT: 8080
